import {
  LayoutDashboard,
  Sliders,
  Layers,
  Key,
  Link2,
  History,
  Settings,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  Plus,
  X,
  Check,
  Copy,
  Search,
  Mic,
  MicOff,
  Play,
  Square,
  Pause,
  Radio,
  Zap,
  Shield,
  ShieldCheck,
  Globe,
  Type,
  Palette,
  LayoutTemplate,
  Clock,
  Download,
  Trash,
  RotateCw,
  ExternalLink,
  MoreHorizontal,
  Menu,
  PanelLeft,
  Sun,
  Moon,
  Monitor,
  User as UserIcon,
  Upload,
  AlertTriangle,
  Info,
  Eye,
  EyeOff,
  Edit,
  Star,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Rocket,
  LogOut,
} from "lucide-react";

export const ICONS = {
  layoutDashboard: LayoutDashboard,
  sliders: Sliders,
  layers: Layers,
  key: Key,
  link2: Link2,
  history: History,
  settings: Settings,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUpRight: ArrowUpRight,
  plus: Plus,
  x: X,
  check: Check,
  copy: Copy,
  search: Search,
  mic: Mic,
  micOff: MicOff,
  play: Play,
  square: Square,
  pause: Pause,
  radio: Radio,
  zap: Zap,
  shield: Shield,
  shieldCheck: ShieldCheck,
  globe: Globe,
  type: Type,
  palette: Palette,
  layout: LayoutTemplate,
  clock: Clock,
  download: Download,
  trash: Trash,
  refresh: RotateCw,
  rotateCw: RotateCw,
  externalLink: ExternalLink,
  moreH: MoreHorizontal,
  menu: Menu,
  panelLeft: PanelLeft,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  user: UserIcon,
  upload: Upload,
  alertTriangle: AlertTriangle,
  info: Info,
  eye: Eye,
  eyeOff: EyeOff,
  edit: Edit,
  star: Star,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
  rocket: Rocket,
  logOut: LogOut,
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  size = 18,
  className,
  ...rest
}: {
  name: IconName;
  size?: number;
  className?: string;
} & React.SVGProps<SVGSVGElement>) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp size={size} strokeWidth={1.75} className={className} {...(rest as any)} />;
}
